### ISSUE TITLE
sh: reveal: No such file or directory

### ISSUE THREAD

**Issue by diegovogel** [Kalaschnik/adobe-fonts-revealer#10]
After installing via Homebrew and running `sh reveal` or `sh reveal.sh` I get this: `sh: reveal: No such file or directory`.

Running macOS 12.6

**Comment by almostsultry** [comment]
Same here. Where is this shell script installed? Search can't find it anywhere including hidden files.

**Comment by dhnyny** [comment]
Same

**Comment by ghost** [comment]
same here!

**Comment by smokingweb** [comment]
That's because the instructions tell you just to install lcdf-typetools, which is only a prerequisite.

Once you've done that you have to open a new window of your terminal and:

1. create a directory in which you will download the adobe-fonts-revealer files:
`mkdir adobe-fonts-revealer`

2. download the files in that directory:
`git clone https://github.com/kalaschnik/adobe-fonts-revealer.git adobe-fonts-revealer`

3. go into the directory:
`adobe-fonts-revealer`

4. launch the command:
`sh reveal`

**Comment by kalaschnik** [comment]
Thanks for clarifying this @smokingweb
