### ISSUE TITLE
New location

### ISSUE THREAD

**Issue by JamaicanRumCream** [Kalaschnik/adobe-fonts-revealer#16]
Fonts are also added to a folder `.w/`, can you add support for this folder?

**Comment by ghost** [comment]
In order to make this change and futureproof in case Adobe decides to add more font directories, you can make these two simple changes:

Change line 14 to `cd $HOME/Library/Application\ Support/Adobe/CoreSync/plugins/livetype/`

Change line 17 to `find . -type f -iname "*.otf" | while read file`

These will look in the livetype directory as well as all subdirectories for OTF files.

**Comment by different55** [comment]
That works great!

From what I can tell, .r is for fonts that have been installed and are available for all local applications, .w is for fonts that have only been activated for/by Adobe apps.

**Comment by kalaschnik** [comment]
merged
